using HSE.RP.API.Models.Payment.Response;
using HSE.RP.Domain.Entities;

namespace HSE.RP.API.Models.DynamicsSynchronisation;

public record BuildingProfessionApplicationWrapper(BuildingProfessionApplicationModel Model, DynamicsBuildingProfessionApplication DynamicsBuildingProfessionApplication);

public record BuildingProfessionApplicationPayment(string BuildingProfessionApplicationId, PaymentResponseModel Payment);

public record BuildingInspectorRegistrationClassWrapper(BuildingProfessionApplicationModel BuildingProfessionApplicationModel, DynamicsBuildingInspectorRegistrationClass dynamicsBuildingInspectorRegistrationClass);

public record GovukPaymentApplicationModel(BuildingProfessionApplicationModel BuildingProfessionApplicationModel, DynamicsBuildingProfessionApplication DynamicsBuildingProfessionApplication);

public record ContactWrapper(Contact Model, DynamicsContact DynamicsContact);

