trigger:
- main
- release-*
- hotfix-*

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: AngularTools
    type: git
    name: 'BSR-AlphaBetaImplementation/AngularTools'
    ref: refs/heads/main

extends:
  template: /pipelines/swa_template.yml@AngularTools  
  parameters:
    projectName: 'RP'
